---
- name: Add Caddy official repository
  apt_repository:
    repo: deb [trusted=yes] https://apt.fury.io/caddy/ /
    state: present

- name: Install Caddy
  apt:
    name: caddy

- name: Enable Caddy
  service:
    name: caddy
    enabled: yes

- name: Configure Caddy
  copy:
    src: Caddyfile
    dest: /etc/caddy/Caddyfile
    mode: 0644
    owner: root
  notify: Restart caddy

- name: Configure Caddy
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/ttrss.caddy
  notify: Restart caddy
