---
- name: Remove previous versions of Docker
  apt:
    name: "{{ packages }}"
    purge: yes
    state: absent
  vars:
    packages:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc

- name: Set Docker repository GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker official repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    state: present

- name: Install Docker
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Enable service "docker"
  systemd:
    name: docker
    enabled: yes

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: Add the remote user to the group "docker"
  user:
    name: "{{ host_remote_user }}"
    group: docker

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Install Docker Machine
  get_url:
    url: https://github.com/docker/machine/releases/download/v0.16.1/docker-machine-Linux-x86_64
    dest: /usr/local/bin/docker-machine
    mode: '0755'
